const Foods = [
    {
      id: 1,
      title: 'yumurta ekmek',
      category: 'Kahvalti',
      price: 15.99,
      img: 'https://cdn.yemek.com/mnresize/1250/833/uploads/2014/05/anne-usulu-yumurtali-ekmek-tarifi-yemekcom.jpg',
      desc: `Bol yumurtali çitir yumurtali ekmek`,
    },
    {
      id: 2,
      title: 'hamburger',
      category: 'Yemek',
      price: 13.99,
      img: 'https://cdn.yemek.com/mncrop/940/625/uploads/2016/05/ev-yapimi-hamburger.jpg',
      desc: `büyük köfteli bol soslu dev hamburger `,
    },
    {
      id: 3,
      title: 'çilekli milkshake',
      category: 'Icecek',
      price: 6.99,
      img: 'https://im.haberturk.com/2020/08/26/ver1598418361/2783707_620x410.jpg',
      desc: `Yaz aylariinin serinletici lezzetlerinden çilekli milkshake.`,
    },
    {
      id: 4,
      title: 'diyet kornfleks',
      category: 'Kahvalti',
      price: 20.99,
      img: 'https://assets.kulinaria.bg/attachments/pictures-images/0000/4664/MAIN-kornfleyks.jpg?1431679212',
      desc: `Formunu korumak isteyenler için, `,
    },
    {
      id: 5,
      title: 'lazanya',
      category: 'Yemek',
      price: 22.99,
      img: 'https://i2.milimaj.com/i/milliyet/75/0x410/5ebaa79055428519a8ccbe8f.jpg',
      desc: `İtalya'nin meşhur lezzetlerinden biri`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'Icecek',
      price: 18.99,
      img: 'https://cdn.yemek.com/mncrop/940/625/uploads/2015/02/oreo-milkshake-tarifi.jpg',
      desc: `Kremali bisküvi Oreo'yu milkshake tarifine katip bekletmeden servis e`,
    },
    {
      id: 7,
      title: 'Menemen ',
      category: 'Kahvalti',
      price: 8.99,
      img: 'https://i.lezzet.com.tr/images-xxlarge-recipe/menemen-4b718aac-cb07-488f-8346-3a504bfb67ef.jpg',
      desc: `Soğansiz menemen `,
    },
    {
      id: 8,
      title: 'Orman Kebabi',
      category: 'Yemek',
      price: 12.99,
      img: 'https://gaziantepetyemekleri.com/wp-content/uploads/2020/05/maxresdefault-9.jpg',
      desc: `Bol sebzeli patatesli orman kebabı  `,
    },
    {
      id: 9,
      title: 'Renkli Milkshake',
      category: 'Icecek',
      price: 16.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYp-NDaXMJZDB4V3EtjivKTCF0zK14CfAS1g&usqp=CAU',
      desc: `Karişik meyveli serinleten lezzet`,
    },
  ];
  export default Foods;